application: newscontrol
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img
  expiration: "1d"

- url: /feeds
  script: feeds.app

- url: /.*/feeds/.*
  script: entries.app

- url: /feeds/.*/entries/.*/tags/.*
  script: entries.app
  
- url: /.*/feeds/.*
  script: feeds.app
  
- url: /tags
  script: tags.app

- url: /tags/.*
  script: tags.app

- url: /news
  script: news.app

- url: /(.*)/(.*)\.rss
  script: rss.app

- url: /login
  script: login.app

- url: /logout
  script: logout.app

- url: /me
  script: me.app

- url: /cron/fetch_feeds.*
  script: cron.app
  login: admin

- url: /
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest